const denominations=[1000,500,200,100,50,20,10,5];
const AED=new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED'});
let records=JSON.parse(localStorage.getItem('collectionRecords')||'[]');
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function num(v){return Number(v||0)}
function save(){localStorage.setItem('collectionRecords',JSON.stringify(records));renderAll()}
function init(){document.querySelector('input[name=date]').valueAsDate=new Date();document.querySelector('input[name=time]').value=new Date().toTimeString().slice(0,5);$('#sheetUrl').value=localStorage.getItem('sheetUrl')||'';$('#denoms').innerHTML=denominations.map(d=>`<div class="denom"><b>AED ${d}</b><input name="qty_${d}" type="number" min="0" value="0"><span id="total_${d}">AED 0.00</span></div>`).join('')+`<div class="denom"><b>Coins</b><input name="coins" type="number" step="0.01" value="0"><span id="total_coins">AED 0.00</span></div>`;$$('input,select,textarea').forEach(x=>x.addEventListener('input',calc));renderAll();}
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(p=>p.classList.remove('active'));$('#'+b.dataset.page).classList.add('active')});
function calc(){let cash=0;denominations.forEach(d=>{let t=num(document.querySelector(`[name=qty_${d}]`).value)*d;cash+=t;$('#total_'+d).textContent=AED.format(t)});cash+=num(document.querySelector('[name=coins]').value);$('#total_coins').textContent=AED.format(num(document.querySelector('[name=coins]').value));let card=['visa','mastercard','amex','tpv','otherCard'].reduce((s,n)=>s+num(document.querySelector(`[name=${n}]`).value),0);let foreign=['usd','gbp','eur','sar','omr','kwd','bhd','qar'].reduce((s,n)=>s+num(document.querySelector(`[name=${n}]`).value),0);let grand=cash+card+foreign;let diff=grand-num(document.querySelector('[name=expectedTotal]').value);$('#cashTotal').textContent=AED.format(cash);$('#cardTotal').textContent=AED.format(card);$('#foreignTotal').textContent=AED.format(foreign);$('#grandTotal').textContent=AED.format(grand);$('#difference').textContent=AED.format(diff);return{cash,card,foreign,grand,diff}}
$('#collectionForm').onsubmit=async e=>{e.preventDefault();let fd=new FormData(e.target), totals=calc();let record=Object.fromEntries(fd.entries());record.id='DC-'+Date.now();record.createdAt=new Date().toISOString();record.status='Pending';Object.assign(record,totals);denominations.forEach(d=>record[`total_${d}`]=num(record[`qty_${d}`])*d);records.unshift(record);save();await pushToSheet(record);alert('Submitted successfully');e.target.reset();init();};
async function pushToSheet(record){let url=localStorage.getItem('sheetUrl');if(!url)return;try{await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)})}catch(e){console.warn('Sheet sync failed',e)}}
function renderAll(){let total=(k)=>records.reduce((s,r)=>s+num(r[k]),0);$('#kpiCash').textContent=AED.format(total('cash'));$('#kpiCard').textContent=AED.format(total('card'));$('#kpiGrand').textContent=AED.format(total('grand'));$('#kpiDiff').textContent=AED.format(total('diff'));renderTable('#latestTable',records.slice(0,8));renderTable('#reportTable',filterRecords())}
function filterRecords(){let q=($('#search')?.value||'').toLowerCase();return records.filter(r=>JSON.stringify(r).toLowerCase().includes(q))}
$('#search').oninput=renderAll;
function renderTable(sel,rows){let cols=['date','time','store','posId','cashier','manager','cash','card','foreign','grand','diff','status'];let h='<tr>'+cols.map(c=>`<th>${c}</th>`).join('')+'</tr>';let b=rows.map(r=>'<tr>'+cols.map(c=>`<td>${['cash','card','foreign','grand','diff'].includes(c)?AED.format(num(r[c])):(r[c]||'')}</td>`).join('')+'</tr>').join('');$(sel).innerHTML=h+b}
$('#exportCsv').onclick=()=>{let cols=['id','date','time','store','department','posId','cashier','manager','shift','floatAmount',...denominations.flatMap(d=>[`qty_${d}`,`total_${d}`]),'coins','cash','visa','mastercard','amex','tpv','otherCard','card','usd','gbp','eur','sar','omr','kwd','bhd','qar','foreign','grand','expectedTotal','diff','status','comment','createdAt'];let csv=[cols.join(',')].concat(records.map(r=>cols.map(c=>`"${String(r[c]??'').replaceAll('"','""')}"`).join(','))).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='daily_collection_export.csv';a.click();};
$('#clearData').onclick=()=>{if(confirm('Clear all local records?')){records=[];save()}};
$('#saveSheetUrl').onclick=()=>{localStorage.setItem('sheetUrl',$('#sheetUrl').value.trim());alert('Backend URL saved')};
init();calc();
